import type { Lesson } from "@/engine/content/types";

export const publishingYourWork: Lesson = {
  id: "creating-with-ai-06",
  slug: "publishing-your-work",
  title: {
    ja: "作品を公開するとき — 各サービスのAI方針、表示、批判への向き合い方、制作記録",
    en: "Publishing Your Work: Platform AI Policies, Labels, Handling Criticism, and Keeping Records",
  },
  summary: {
    ja: "pixivの「AI生成作品」設定、noteの学習拒否と対価還元、MetaのAI表示、YouTubeの収益化ポリシー。どこに出すかでルールが違い、表示は削除ではなく文脈のためにある。批判には制作記録で答える。",
    en: "pixiv's AI-generated setting, note's training opt-out and compensation program, Meta's AI label, YouTube's monetization policy. Rules differ by venue, and labels exist to add context rather than to remove posts. Answer criticism with your process records.",
  },
  body: {
    ja: `## 出す場所のルールを読み、表示を付け、記録を残す

このトラックで見てきたように、AIの扱いは公開先ごとに違います。文章の公募と電子書籍は[文章を書く相棒としてのAI](/ja/learn/creating-with-ai/writing-with-ai)、音楽の配信は[音楽を作る](/ja/learn/creating-with-ai/making-music)、動画サイトの開示は[動画を作る](/ja/learn/creating-with-ai/making-video)、ゲームの販売サイトとジャムは[ゲーム・コードで作る](/ja/learn/creating-with-ai/games-and-creative-coding)のレッスンで扱いました。ここでは、イラスト・文章・SNSの投稿先の例と、公開した後の心構えをまとめます。

> **ご注意**: 以下は2026年10月時点の各社が公開しているルールの紹介です。公開前に最新の原文を確かめてください。

### pixiv — 「AI生成作品」の設定
pixivは2022年10月31日に、投稿時に**AI生成作品**であることを示す設定、AI生成作品を表示するかどうかを選べる閲覧者側の設定、AI生成作品だけを分けたランキングを導入しました。AI生成作品の定義は「制作過程のすべて、もしくはほとんどをAIによって生成された作品」です。2026年2月18日の告知では、閲覧数や反応を得るために作品の内容と食い違う設定を付ける例や、宣伝目的で過剰な数の作品を投稿する例が確認されたとして、3月18日にガイドラインを改定しました。年齢制限・オリジナル作品設定・**AI生成作品設定**・ジャンル・タグなどに、作品の内容と一致しない設定を付ける行為と、宣伝目的で他の利用者に大きな影響を与えるほど大量に投稿する行為が、明確に禁止事項になりました。あわせて、規約・ガイドラインに違反した可能性が高い作品を検索結果から隠す設定（初期設定は非表示）を同年3月から順次提供し、検知の基準は回避を防ぐため公開しないとしています。

AIで作った絵をAI生成でないと申告することも、その逆も違反です。設定は正直に、が唯一の正解です。

### note — 自分の作品が学習に使われるかを選ぶ
文章の投稿先では、自分の作品がAIの学習に使われるかどうかも問題になります。noteは2025年2月13日、アカウント設定で「生成AIの学習に拒否意向を示す」をオンにできるようにしました。これは外部のAI事業者に意向を示すもので、すべての事業者が必ず従うことを保証するものではないと明記されています。さらに2025年6月17日には、投稿されたテキストをnoteと契約したAI事業者に学習データとして提供し、得た収益から手数料を除いた分をクリエイターに還元する**AI学習対価還元プログラム**を発表しました。対象は無料・有料・メンバーシップ特典を含むテキストで、画像・音声・動画は含まれません。参加は初期設定でオンになっており、アカウント設定で参加しないよう変更でき、6月30日からは記事ごとの設定もできるとしています。

自分の作品を学習に使わせるかどうかを、サービスの設定で自分で決められるようになってきています。日本の著作権法第30条の4と、JASRACが求めている改正については、[日本の著作権法とAI](/ja/learn/generative-media/copyright-in-japan)と[音楽を作る](/ja/learn/creating-with-ai/making-music)のレッスンを参照してください。

### SNS — 表示は「削除」ではなく「文脈」のため
Metaは2024年4月5日に、Facebook・Instagram・ThreadsでAIで作られた画像などに「Made with AI」の表示を付ける方針を発表し、業界で共有される信号（コンテンツクレデンシャルなど）の検出と、投稿者の自己申告の二つを根拠にするとしました。同年7月1日には表示名を「AI info」に改め、軽い修整だけの内容では表示を投稿メニューの中に移しています。重要なのは、Metaがこうしたコンテンツを、ほかのポリシーに違反しない限り**削除せずに、表示と文脈を付けて残す**と明言している点です。表示は罰ではなく、見る人への情報です。

### YouTube — 「本物でない」量産は収益化できない
YouTubeパートナープログラムの収益化ポリシーは、2025年7月15日に「繰り返しの多いコンテンツ」の項目を「**本物でないコンテンツ**」に改め、大量生産された、または繰り返しの多いコンテンツが対象だと明確にしました。例として、低い教育的価値や最小限の変化しかない似た動画の繰り返し、画像のスライドショーや型どおりの筋書き、そして**汎用的で独自性のないテンプレートで作られ、大量生産の印象を与えるAI生成コンテンツ**を挙げています。一方、決まったイントロやアウトロがあっても中身が実質的に違う動画、決まったキャラクターで毎回違う物語を描くシリーズは収益化できます。「AIを使ったか」ではなく、「中身が実質的に異なり、創造的・教育的な価値を届けているか」が基準です。

### 批判への向き合い方
AIを使った作品には、作風の模倣や学習データの問題を背景に、強い反発が向くことがあります。
- **先に示す**: AIを使ったことは、公開先の設定や説明文で先に示します。あとから分かるのが最も信頼を失います。「人間が作った」と偽ることは、画像生成サービスのポリシーでも禁じられています（[画像を作る](/ja/learn/creating-with-ai/making-images)のレッスン参照）。
- **場を選ぶ**: AI作品を受け付けない公募・ジャム・コミュニティがあります。そのルールは尊重し、受け付けている場に出します。
- **過程で答える**: 「どこまで自分で作ったか」を問われたら、下の制作記録で具体的に答えます。
- **人の作品を踏まない**: 特定の作家の名前を挙げてまねる、他人の作品を参考画像にして似せる、実在の人の顔や声を無断で使う——批判の多くはここに向きます。[画像を作る](/ja/learn/creating-with-ai/making-images)・[動画を作る](/ja/learn/creating-with-ai/making-video)のレッスンの確認を済ませておきます。

### 制作記録に残すもの
- 使ったツール・プラン・日付。
- プロンプトと設定（シード値、参考画像とその出どころ、使ったモデルの名称）。
- 生成物の原本と、自分が加筆・修正・選択した過程（下書き、レイヤー、タイムラプス、Gitの履歴）。
- 公開先に申告した内容の控え。

文化庁のチェックリストも、生成に使ったプロンプトなどを後から確かめられるようにしておくことを勧めています（[資料・画像づくり](/ja/learn/ai-at-work/slides-and-images)のレッスン参照）。記録は、著作物性の説明（人が創作的に加筆・修正した部分）、公募での提出の求め、配信先からの問い合わせ、そして読者への説明のすべてに使えます。`,
    en: `## Read the venue's rules, add the label, keep the records

As this track has shown, each venue treats AI differently. Writing contests and e-books were covered in [writing with AI](/en/learn/creating-with-ai/writing-with-ai), music distribution in [making music](/en/learn/creating-with-ai/making-music), video-site disclosure in [making video](/en/learn/creating-with-ai/making-video), and game stores and jams in [games and creative coding](/en/learn/creating-with-ai/games-and-creative-coding). This lesson covers examples for illustration, text, and social media, and the mindset for after you publish.

> **Please note**: these are the rules as published by each company in October 2026. Check the current originals before you publish.

### pixiv: the "AI-generated" setting
On October 31, 2022, pixiv introduced a setting that marks a work as **AI-generated** at upload, a viewer-side setting for whether to show AI-generated works, and a separate ranking for them. It defines an AI-generated work as one whose creation process was entirely or mostly generated by AI. In an announcement on February 18, 2026, pixiv said it had confirmed cases of works posted with settings that did not match their content in order to gain views and reactions, and of excessive numbers of works posted for promotion, and revised its guidelines on March 18. Adding settings that do not match the work — age restriction, original-work status, the **AI-generated setting**, genre, tags, and the like — and posting in such volume for promotional purposes that it significantly affects other users are now explicit prohibitions. From March of that year it has also been rolling out a search setting that hides works likely to violate its terms or guidelines (hidden by default), and it says the detection criteria will not be published, to prevent circumvention.

Declaring an AI-made picture as not AI-generated is a violation, and so is the reverse. Setting it honestly is the only correct answer.

### note: choosing whether your work trains AI
On text platforms, another question is whether your work is used to train AI. On February 13, 2025, note added an account setting, "indicate that you refuse generative AI training." It is an expression of intent toward outside AI companies, and note states plainly that it does not guarantee every company will comply. Then, on June 17, 2025, note announced its **AI Training Compensation Program**: text posted on note is provided as training data to AI companies under contract with note, and the revenue, less note's fees, is returned to creators. It covers text in free, paid, and membership-only posts; images, audio, and video are excluded. Participation is on by default, can be switched off in account settings, and from June 30 can be set per post.

Whether your work may be used for training is increasingly something you decide yourself in each service's settings. For Article 30-4 of Japan's Copyright Act and the amendment JASRAC is calling for, see [Japanese copyright law and AI](/en/learn/generative-media/copyright-in-japan) and [making music](/en/learn/creating-with-ai/making-music).

### Social media: labels add context, they don't remove posts
On April 5, 2024, Meta announced that it would label AI-made images and similar content on Facebook, Instagram, and Threads as "Made with AI," based on two signals: detection of industry-shared indicators such as Content Credentials, and self-disclosure by the person posting. On July 1 of that year it renamed the label "AI info" and moved it into the post menu for content with only minor retouching. The important point is that Meta says it **keeps such content on its platforms with labels and context** unless it violates other policies. The label is information for viewers, not a penalty.

### YouTube: mass-produced "inauthentic" content can't be monetized
On July 15, 2025, the YouTube Partner Program's monetization policies renamed their "repetitious content" section **"inauthentic content"** to make clear that it covers content that is mass-produced or repetitive. Examples include similar or repetitive videos with low educational value or minimal variation, image slideshows and templated storylines, and **AI-generated content made with generic or unoriginal templates that gives the impression of mass production**. By contrast, videos with a consistent intro and outro but materially different core content, or a series with set characters and a distinct story in each episode, can be monetized. The test is not whether AI was used but whether the substance is materially varied and delivers creative, educational, or other value.

### Facing criticism
Work made with AI can draw strong pushback, against the background of style imitation and training-data disputes.
- **Say it first**: declare AI use up front, in the venue's setting or your description. Being found out later costs the most trust. Passing work off as human-made is also prohibited by image services' policies (see [making images](/en/learn/creating-with-ai/making-images)).
- **Choose the venue**: some contests, jams, and communities do not accept AI work. Respect those rules and publish where it is accepted.
- **Answer with process**: when asked how much you made yourself, answer concretely from the records below.
- **Don't step on other people's work**: imitating a named artist, feeding someone's work in as a reference to copy it, using a real person's face or voice without permission — most criticism is aimed here. Run the checks in [making images](/en/learn/creating-with-ai/making-images) and [making video](/en/learn/creating-with-ai/making-video) first.

### What to keep in your process records
- The tool, plan, and date.
- Prompts and settings (seed values, reference images and their sources, the name of the model used).
- The raw output and the trail of what you added, changed, and selected (drafts, layers, time-lapses, Git history).
- A copy of what you declared to each venue.

The Agency for Cultural Affairs' checklist also recommends keeping prompts so the generation process can be checked later (see [making slides and images](/en/learn/ai-at-work/slides-and-images)). Records serve every purpose at once: explaining copyrightability (the parts a person creatively added or edited), a contest's request for submissions, a platform's inquiry, and your own explanation to readers.`,
  },
  quiz: [
    {
      kind: "multi",
      prompt: {
        ja: "pixivのガイドライン（2026年3月改定）で禁止されている行為をすべて選んでください。",
        en: "Which of the following does pixiv's guideline (revised March 2026) prohibit? Select all that apply.",
      },
      choices: [
        {
          ja: "制作過程のほとんどをAIで生成した作品を、AI生成作品設定をオフにして投稿する",
          en: "Posting a work generated mostly by AI with the AI-generated setting turned off",
        },
        { ja: "手描きの作品に、AI生成作品設定を付けて投稿する", en: "Posting a hand-drawn work with the AI-generated setting turned on" },
        { ja: "AI生成作品設定をオンにして、AI生成作品として投稿する", en: "Posting an AI-generated work with the AI-generated setting turned on" },
        {
          ja: "宣伝目的で、他の利用者に大きな影響を与えるほど大量に投稿する",
          en: "Posting in such volume for promotional purposes that it significantly affects other users",
        },
      ],
      correctIndexes: [0, 1, 3],
      explanation: {
        ja: "改定後のガイドラインは、AI生成作品設定を含む各種の設定に作品の内容と一致しない設定を付ける行為（AI生成を非AIと申告することも、その逆も）と、宣伝目的の大量投稿を禁止事項としています。設定を正しく付けてAI生成作品として投稿すること自体は認められています。",
        en: "The revised guideline prohibits settings that do not match the work, including the AI-generated setting in either direction, and mass posting for promotion. Posting an AI-generated work with the setting correctly turned on is allowed.",
      },
    },
    {
      kind: "boolean",
      prompt: {
        ja: "Metaの「AI info」表示は、AIで作ったと分かった投稿を削除するための仕組みである。",
        en: "Meta's \"AI info\" label is a mechanism for removing posts found to be AI-made.",
      },
      answer: false,
      explanation: {
        ja: "Metaは、AIで作られたコンテンツを、ほかのポリシーに違反しない限り削除せずに、表示と文脈を付けて残すと明言しています。表示は見る人への情報であって、罰ではありません。",
        en: "Meta states that it keeps AI-made content on its platforms with labels and context unless it violates other policies. The label is information for viewers, not a penalty.",
      },
    },
  ],
  sources: [
    {
      label: "pixiv: pixivにおける新しい検索設定の追加と、ガイドライン改定の予定について（2026-02-18）",
      url: "https://www.pixiv.net/info.php?id=13316",
    },
    { label: "note公式: AI学習対価還元プログラムの開始について（2025-06-17）", url: "https://note.com/info/n/n49bbcbdefe1a" },
    {
      label: "Meta: Our Approach to Labeling AI-Generated Content and Manipulated Media（2024-04-05、2024-07-01 更新）",
      url: "https://about.fb.com/news/2024/04/metas-approach-to-labeling-ai-generated-content-and-manipulated-media/",
    },
    {
      label: "YouTube Help: YouTube channel monetization policies（Inauthentic content）",
      url: "https://support.google.com/youtube/answer/1311392?hl=en",
    },
  ],
  lastVerified: "2026-10-11",
  glossaryRefs: [
    "ai-generated-work-setting",
    "ai-training-opt-out",
    "ai-content-label",
    "inauthentic-content",
    "content-credentials",
    "article-30-4",
  ],
};
