import type { Lesson } from "@/engine/content/types";

export const deepfakesAndProvenance: Lesson = {
  id: "generative-media-07",
  slug: "deepfakes-and-provenance",
  title: {
    ja: "ディープフェイクと来歴情報 — その画像・動画・声は本物か",
    en: "Deepfakes and Content Provenance: Is It Real?",
  },
  summary: {
    ja: "AIで作られた偽の画像・動画・音声は、人の目でも検出ツールでも見抜きにくい。「見抜く」より「確かめる」ための仕組みと習慣。",
    en: "AI-made fake images, video, and audio are hard to spot by eye or by detector. The mechanisms and habits for checking rather than guessing.",
  },
  body: {
    ja: `## 「見ればわかる」は通用しない

画像・動画・音声の生成技術（このトラックの前半のレッスン参照）が進み、実在の人物が言っていないことを言わせる動画や、家族の声をまねた電話まで作れるようになりました。本物のように見せかけたAI生成・加工のコンテンツを**ディープフェイク**と呼びます。米連邦捜査局（FBI）は2024年12月の注意喚起で、身近な人の声をまねた短い音声で緊急事態を装い、すぐの送金や身代金を求める手口や、企業幹部や警察などを装ったリアルタイムのビデオ通話といった詐欺の手口を挙げています。

### 検出ツールには限界がある
「AIが作ったかどうか」を判定するツールはありますが、米国国立標準技術研究所（NIST）が2024年11月に公表した報告書は、自動検出は検出側と生成側の**いたちごっこ**で、新しい検出法ができても生成モデルが進歩し、攻撃者も回避法を学ぶこと、検出器は特定の生成モデルでしかうまく働かないことが多いことを指摘しています。人間が作ったものをAI製と誤って判定する**偽陽性**は、深刻な害になりうるとも述べています。どの技術も単独では万能ではない、というのが報告書の立場です。検出ツールの結果は「参考」であって「判定」ではありません。

### 来歴（プロヴナンス）を確かめる仕組み
そこで、後から見抜くのではなく、作られたときの情報を**記録して確かめる**仕組みが広がっています。
- **コンテンツクレデンシャル（C2PA）**: 業界団体C2PAが定める標準です。誰が・どのツールで作り・どう編集したかという来歴を、**暗号で結びつけた**記録としてファイルに付けます。対応するファイルは、Content Authenticity Initiativeの確認ツール（contentcredentials.org/verify）などで中身を見られます。ただし、C2PAの解説自身が、来歴情報だけでは内容が**真実かどうかはわからない**こと、来歴情報は**削除できる**こと、付けるかどうかは任意で、付いていないものを一律に疑う仕組みを意図していないことを明記しています。NISTの報告書も、SNSなどで共有されるときにメタデータが丸ごと削除されることが多いと指摘しています。
- **電子透かし（SynthID）**: Googleは、自社のAIモデルで生成したコンテンツに、利用者には見えない電子透かし（SynthID）を直接埋め込んでいます。Geminiアプリにファイルを見せて「Google AIで作成・編集されたか」を尋ねると確認できます。ただし、現在見分けられるのは**GoogleのAIツールで作られたものだけ**で、透かしが見つからなくても、他社のAIで作られた可能性は残ります。加工を何度も重ねると、透かしが検出されなくなることもあります。

EUのAI Actも、ディープフェイクにAIで生成・加工したものだと表示することなどを求めています（AIのルールのレッスン参照）。

### 確かめる習慣
- **感情を揺さぶる・急がせる内容ほど、一呼吸おく**: 怒りや恐怖をかき立て、すぐの拡散や送金を求めるものほど要注意です。
- **出どころをたどる**: 最初に誰が発信したか、信頼できる報道機関や公式アカウントが伝えているかを確かめる。画像検索で、同じ画像が以前から別の文脈で出回っていないか調べるのも手です。
- **来歴情報と透かしは手がかりの一つ**: 「付いていない＝偽物」でも「付いている＝真実」でもありません。
- **声や映像で送金を求められたら、いったん切る**: FBIは、いったん電話を切り、相手を名乗る銀行や組織の連絡先を自分で調べて直接かけ直すこと、本人確認のための**合言葉**を家族で決めておくことを勧めています。日本で被害の大きい手口と相談先は[AIを使った詐欺](/ja/learn/ai-and-society/ai-scams)のレッスンで扱います。`,
    en: `## "I'll know it when I see it" no longer works

Image, video, and audio generation (earlier lessons in this track) has advanced to the point where it can make a real person appear to say things they never said, or imitate a family member's voice on the phone. AI-generated or manipulated content made to pass as real is called a **deepfake**. In a December 2024 public service announcement, the US Federal Bureau of Investigation (FBI) described fraud schemes such as short audio clips in a loved one's voice, faking a crisis to demand immediate money or a ransom, and real-time video calls with people posing as company executives or law enforcement.

### Detectors have limits
Tools exist that try to tell whether something was made by AI. But a report published by the US National Institute of Standards and Technology (NIST) in November 2024 describes automated detection as a **cat-and-mouse game**: as soon as a new detection method appears, generation models improve and adversaries learn to evade it, and detectors often work well only on specific generators. It also warns that **false positives** — judging human-made content to be AI-generated — can be extremely damaging. In the report's view, no technique is a complete solution on its own. Treat a detector's output as a hint, not a verdict.

### Checking provenance instead
So instead of trying to catch fakes after the fact, a different approach is spreading: **recording how content was made and letting people check it**.
- **Content Credentials (C2PA)**: a standard from the industry coalition C2PA. It attaches a **cryptographically bound** record of provenance — who made the content, with what tool, and how it was edited — to the file. For supported files, you can inspect the record with tools such as the Content Authenticity Initiative's Verify site (contentcredentials.org/verify). But C2PA's own explainer states that provenance information alone **cannot tell you whether content is true**, that provenance metadata **can be removed**, and that adding it is optional — the standard is not meant to make everything without credentials automatically suspect. The NIST report likewise notes that metadata is often stripped entirely when files are shared, for example on social media.
- **Watermarks (SynthID)**: Google embeds a digital watermark that is not visible to users, SynthID, directly into content generated by its AI models. You can upload a file to the Gemini app and ask whether it was created or edited with Google AI. But Gemini can currently recognize **only content created with Google's AI tools**: if no watermark is found, the content could still come from another company's AI. After many alterations, the watermark may also go undetected.

The EU AI Act also requires, among other things, that deepfakes be disclosed as AI-generated or manipulated (see the lesson on the rules for AI).

### Habits for checking
- **Slow down when content is emotional or urgent**: be most careful with anything that stirs anger or fear and pushes you to share or pay right away.
- **Trace the source**: who posted it first, and are reliable news outlets or official accounts reporting it? A reverse image search can show whether the same image was circulating earlier in a different context.
- **Treat provenance and watermarks as one clue among several**: missing credentials don't mean fake, and present credentials don't mean true.
- **If a voice or video asks for money, hang up first**: the FBI advises hanging up, looking up the bank's or organization's contact details yourself and calling them directly, and agreeing on a **secret word or phrase** with your family to verify identity. For the scams doing the most damage in Japan and where to get help, see the [AI-enabled scams](/en/learn/ai-and-society/ai-scams) lesson.`,
  },
  quiz: [
    {
      kind: "boolean",
      prompt: {
        ja: "コンテンツクレデンシャル（来歴情報）が付いていない画像は、AIで作られた偽物だと判断できる。",
        en: "An image without Content Credentials can be judged to be an AI-made fake.",
      },
      answer: false,
      explanation: {
        ja: "来歴情報を付けるかどうかは任意で、SNSで共有されるときなどに削除されることも多くあります。付いていないことだけで判断せず、出どころなど他の手がかりと合わせて確かめます。",
        en: "Adding provenance is optional, and it is often stripped when files are shared, for example on social media. Don't judge by its absence alone; combine it with other clues such as where the content came from.",
      },
    },
    {
      kind: "single",
      prompt: {
        ja: "家族を名乗る電話で、声はそっくりなのに急な送金を求められた。FBIの注意喚起に沿った対応は？",
        en: "A caller claiming to be a family member sounds exactly like them and urgently asks for money. What does the FBI's advice suggest?",
      },
      choices: [
        {
          ja: "いったん電話を切って自分で確かめた番号にかけ直すか、家族で決めた合言葉で確認する",
          en: "Hang up and call back on a number you've verified yourself, or check with a secret word agreed within your family",
        },
        { ja: "声がそっくりなら本人なので、すぐに送金する", en: "If the voice matches, it must be them — send the money right away" },
        {
          ja: "AI検出ツールで通話の音声を調べ、「本物」と出たら送金する",
          en: "Run the call audio through an AI detector and pay if it says the voice is real",
        },
      ],
      correctIndex: 0,
      explanation: {
        ja: "声は短い音声からでもまねられ、検出ツールも万能ではありません。別の経路での確認と合言葉が有効です。",
        en: "A voice can be imitated from short clips, and detectors aren't reliable enough to settle it. Verify through another channel and use a secret word.",
      },
    },
  ],
  sources: [
    {
      label: "NIST: Reducing Risks Posed by Synthetic Content (NIST AI 100-4, 2024)",
      url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-4.pdf",
    },
    { label: "C2PA: Content Credentials Explainer", url: "https://spec.c2pa.org/specifications/specifications/2.4/explainer/Explainer.html" },
    {
      label: "Gemini Apps Help: Verify AI-generated images, videos, and audio",
      url: "https://support.google.com/gemini/answer/16722517?hl=en",
    },
    {
      label: "FBI IC3: Criminals Use Generative Artificial Intelligence to Facilitate Financial Fraud (2024-12-03)",
      url: "https://www.ic3.gov/PSA/2024/PSA241203",
    },
  ],
  lastVerified: "2026-10-07",
  glossaryRefs: ["deepfake", "content-credentials", "digital-watermark"],
};
